### ISSUE TITLE
**[PROPOSAL]** Filtering out certain JobFailed events

### ISSUE THREAD

**Issue by scottconnerly** [spatie/laravel-failed-job-monitor#10]
**In raising this issue, I confirm the following (please check boxes):**
- [X] I have read and understood the [contributors guide]().
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X] I have checked that the bug-fix I am reporting can be replicated.
- [X] I have sent a postcard of my hometown.

---

I would like to propose adding of an optional callback function in FailedJobNotifier::notifyIfJobFailed() which:
- Takes both $event and $sender as arguments
- Returns a boolean as to whether or not to send the message
- The callback function itself could be specified in the config.

---

Why do I propose this?

Because some of the exceptions in our queued jobs we are handling gracefully otherwise. The unexpected ones are the ones we need to get emails about. With such a callback, we could filter out the exception messages we are already accounting for.

Thank you,
Freddy Kruger Potato Jacket Scott

**Comment by freekmurze** [comment]
Sounds good, I'd accept a PR for that.
