### ISSUE TITLE
Use L5.3 native notification capabilites

### ISSUE THREAD

**Issue by freekmurze** [spatie/laravel-failed-job-monitor#11]
Planned features for `v2` of this package:
- make use of L5.3 notification capabilities
- support for < L5.3 may be dropped
- breaking changes are allowed

I'd accept a fully tested PR that implements all this 😄

**Comment by freekmurze** [comment]
If you decide to work on this, leave a note here, so others know somebody picked up the glove.

**Comment by spyric** [comment]
I can do that

**Comment by freekmurze** [comment]
Awesome! Have fun!
