### ISSUE TITLE
Can you add support for Laravel 5.5?

### ISSUE THREAD

**Issue by it-can** [spatie/laravel-failed-job-monitor#34]
Can you add support for Laravel 5.5?

**Comment by freekmurze** [comment]
We were not planning on upgrading this package because Horizon can send out notifications when a job fails. Can you make your app use Horizon?

**Comment by it-can** [comment]
I don't use Horizon...

**Comment by freekmurze** [comment]
I'll try to take care of this soon. If you need this quick feel free to send a PR where you add compatibility with L5.5. If there are any L5.5 specific features you want to use, you're free to drop compatibility with L5.4. Breaking changes are allowed. Everything should be fully tested.

**Comment by ctf0** [comment]
@freekmurze horizon works on redis exclusively and no plans to extend it beyond that in the near future, so ur package fills the gap for those with beanstalked

**Comment by freekmurze** [comment]
@ctf0 true

**Comment by freekmurze** [comment]
Done,  the newly released `v3` is compatible with L5.5
