### ISSUE TITLE
Does not work with Laravel 5.4.X

### ISSUE THREAD

**Issue by jonnyxe** [spatie/laravel-failed-job-monitor#35]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for spatie/laravel-failed-job-monitor ^3.0 -> satisfiable by spatie/laravel-failed-job-monitor[3.0.0].
    - Conclusion: remove laravel/framework v5.4.35
    - Conclusion: don't install laravel/framework v5.4.35
    - spatie/laravel-failed-job-monitor 3.0.0 requires illuminate/notifications ~5.5.0 -> satisfiable by laravel/framework[5.5.x-dev], illuminate/notifications[5.5.x-dev, v5.5.0, v5.5.2].
    - Can only install one of: laravel/framework[5.5.x-dev, v5.4.35].
    - don't install illuminate/notifications 5.5.x-dev|don't install laravel/framework v5.4.35
    - don't install illuminate/notifications v5.5.0|don't install laravel/framework v5.4.35
    - don't install illuminate/notifications v5.5.2|don't install laravel/framework v5.4.35
    - Installation request for laravel/framework (locked at v5.4.35, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.35].

**Comment by freekmurze** [comment]
For Laravel 5.4 you need to install v2 of the package.
