### ISSUE TITLE
Feature suggestion: ability to conditionally turn notifications off

### ISSUE THREAD

**Issue by jkudish** [spatie/laravel-failed-job-monitor#38]
It'd be great if there was an env variable I could set to essentially turn off the package for local development. The main reason I'd want this is to be able to work offline and still see what my errors are. Right now I get a Guzzle error because it can't reach the slack webhook URL.

**Comment by freekmurze** [comment]
Add accept a non-breaking, fully tested PR that adds that to the package.

**Comment by jkudish** [comment]
Ok awesome, i'll work on it next week

**Comment by freekmurze** [comment]
Let's handle this further in #40
