### ISSUE TITLE
Mail queue failure

### ISSUE THREAD

**Issue by rbruhn** [spatie/laravel-failed-job-monitor#42]
Just a quick question. What if the job failure has to do with the mail queue? What filter would you use to stop it from retrying to send failure after failure?

**Comment by freekmurze** [comment]
> What if the job failure has to do with the mail queue?
Then the mail wouldn't be sent. You could opt to use Slack for your notifications.
>  What filter would you use to stop it from retrying to send failure after failure?
I don't understand this question.
