### ISSUE TITLE
routeNotificationForMail() must be of the type string, array returned

### ISSUE THREAD

**Issue by fridzema** [spatie/laravel-failed-job-monitor#45]
Hello,

I am using this package for a few months and suddenly i get trowed with this error a few times:
```
Symfony\Component\Debug\Exception\FatalThrowableError
Return value of Spatie\FailedJobMonitor\Notifiable::routeNotificationForMail() must be of the type string, array returned
```

Anyone has an idea where to look?

**Comment by amosmos** [comment]
Sorry I can't answer you but wanted to ask - where do you see this error? Since this package really gets working once a job fail, how can you debug and see errors?

Thanks!

**Comment by fridzema** [comment]
@amosmos For me this issue can be closed, i removed the package from my setup

**Comment by amosmos** [comment]
Thanks.

But as I still use it can you perhaps help me out and let me know how you managed to see the error messages from it?

Thanks,
Amos

**Comment by fridzema** [comment]
Hmmm i got those errors when a job failed, after all i think it may had something to do with an outdated config file.

Sentry seems to purged the logs so i cannot find the full stack trace back unfortunately.

**Comment by amosmos** [comment]
Thanks - so you mean you were able to see these errors in Sentry?

**Comment by fridzema** [comment]
I exactly saw the error i posted in sentry, not able to see why the job failed.

**Comment by amosmos** [comment]
Got it. Just was curious about where did you see the error. Thanks!




<http://www.linkedin.com/in/amosshacham>

**Comment by andela-tolotin** [comment]
I think you should check for `FAILED_JOB_SLACK_WEBHOOK_URL` key in your .env file
