### ISSUE TITLE
Send notification to multiple users

### ISSUE THREAD

**Issue by amosmos** [spatie/laravel-failed-job-monitor#49]
Hi,

Thanks for a great package!

Is there a way to send the notification to multiple email addresses?

I saw that the package is using the standard `routeNotificationForMail` method, which I thought can accept a collection of objects with "email" and "name" properties, but that didn't work. I also tried string with commas or semicolons and that didn't work. I also tried simple php array with email addresses but didn't work either.

Do you know if that can work somehow?

Thanks!
Amos

**Comment by amosmos** [comment]
Just thought to check if someone has an idea about this :-)

Thanks!

**Comment by lidoma** [comment]
+1 to this issue. This is exactly what I'm looking for.

**Comment by antoiba86** [comment]
Hello there,
I found a solution to this problem, but you must update the Notifiable class in the vendor folder.
Maybe I will do a pull request later.
