### ISSUE TITLE
[QUESTION] PHP7 - Its just not needed...

### ISSUE THREAD

**Issue by djekl** [spatie/laravel-failed-job-monitor#5]
Your package requires PHP7, and yes I have already read issue #2. However your code in no way uses any PHP7 code, so you are only limiting the number of users who may install it, unless we are using PHP7. Many developers aren't yet using this major version of PHP and with you using absolutely **NO** PHP7 code/features etc. there is just no point for this restriction.

Can you please lower it until such a time as you are using PHP7 code, and can justify any changes to this code. I understand the speed increases etc. that PHP7 has introduced, and I look forward to using it. However my production environment (at this moment in time) cannot be just upgraded to PHP7.

**Comment by freekmurze** [comment]
If you don't agree with our reasoning, you can always fork this repo and maintain your own PHP 5 compatible version.

**Comment by robclancy** [comment]
I think you mean your lack of reasons as you don't actually make any. You describe reasons to use PHP 7 for your application but if you aren't using the PHP7 features yet tell composer it needs PHP7 you are just being dumb and basically lying to composer. I wasn't planning on using this library, was just checking it out and with such stubborn thinking I doubt I will ever use something here. Oneday you might add a feature with no option to turn it off "because you do it in your app" and then blog about it as if that is going to make everything okay.

**Comment by freekmurze** [comment]
You are right the PHP 7 features we use can be easily removed from the code. But with that reasoning we could also remove the usages of `:class`, the short array syntax, etc... If we really wanted we even could add PHP 4 compatibliy. But we as a company don't need that. Requiring PHP 7 is not a problem for our projects. So we have no need to strip functionality that is not present in older PHP versions.

Being able to use scalar type hints and return type in justifies requiring PHP 7 in our opinion. It saves us time and (as a company) money: we can just put our application code in a package, no need to go over it removing type hints and return types and tracking down other usages of PHP 7 functionalities. Being able to use those features allows to create more readable, better code. If you don't agree with that opinion, that's fine. You don't need to use our packages in you don't want to. You are free to fork our code to create your own version.

Your fear that we'll introduce functionality that is breaking is unfounded. For all our packages we follow [semantic versioning](). With [50+ packages released](https://packagist.org/search/?q=spatie&orderBys%5B0%5D%5Bsort%5D=downloads&orderBys%5B0%5D%5Border%5D=desc) and no complaints on breaking changes I think we're doing a good job with that. If you don't want extra features that we introduce in a package, make sure you require the right version in your `composer.json` file. 

In your comment you state that we are "being dumb and basically lying to composer". First, in it's current state this package uses PHP 7 features, so we see no problem requiring that version in composer.json. Secondly, you don't need to agree with every decision that a package creator / maintainer takes, but calling them dumb is not a nice thing to do.  Calling us (or other package creators/maintainers) dumb not only adds nothing to the conversion, it just hurts our motiviation in releasing free software for you.

If you ever have an issue with our software, let us now in a constructive way and we'll try to fix it.  We respond to [all raised issues](). We value [all PR's](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+user%3Aspatie+) that we get.

**Comment by djekl** [comment]
Can be and have been, along with at current 3 other developers forks - https://github.com/alanwynn/laravel-failed-job-monitor

**Comment by robclancy** [comment]
@freekmurze I think you're losing it mate. You see you don't use ANY PHP 7 features. And you know that. You are using PHP 5.x in this library and restricting it to PHP 7 in `composer.json` for stupid reasons as outlined by your blog. I discussed this with other people and they are very confused why you did it, they even came up with possible real reasons that would make sense but not the dribble you wrote about. If you had used a single PHP 7 feature in this library I would never have even commented but stubborn PHP developers enforcing their own ideologies for no real reason annoy me. At least use the feature you claim to use in your damn post.

**Comment by robclancy** [comment]
Maybe if your dumb blog post mentioned you actually used PHP syntax instead of forcing PHP7 on people "because you think they should use it for performance" is the only reason I posted. Instead of writing a long blog post about your weird ideologies you could have simple replied with "we use PHP7 features.
