### ISSUE TITLE
Publishing the config with "--tag=failed-job-monitor-config" doesn't work

### ISSUE THREAD

**Issue by DJoepie** [spatie/laravel-failed-job-monitor#65]
I got it working by publishing with `php artisan vendor:publish --tag=config`
I don't know if this is an error in the documentation.

**Comment by ConnorHowell** [comment]
If anyone runs into this in the future, run `php artisan vendor:publish --provider="Spatie\FailedJobMonitor\FailedJobMonitorServiceProvider"` if you're not running version 4+
