### ISSUE TITLE
Wrong email gets notified

### ISSUE THREAD

**Issue by emildayan** [spatie/laravel-failed-job-monitor#67]
Had to pull this from production as it was causing some scary errors.

Basically, we noticed that it was sending failed jobs notifications to the email specified in config (as it should), but also to random users in our database.

The only thing I can imagine is if there's a caching error at play. 

We use Redis for cache_driver and session_driver.
This occured during a job run via the CLI (queue:work)

The only thing I can imagine is something going wrong with this:
`
            $notifiable = app(config('failed-job-monitor.notifiable'));`

But I'm totally lost in this error and how to possibly look for what can be wrong.
Eventually, running php artisan queue:restart let go of the incorrect email, and emails were coming only to the correct address.

Very much appreciate any help here even though the explanation is terrible.

Thanks!

**Comment by emildayan** [comment]
The additional email(s) that were notified incorrectly DID receive another notification (via $user->notify) prior to the job failing.
Can this have been cached somehow?

Meaning, a user received a forgot password notification 12:00
An unrelated cron-job, run via CLI, fails at 12:10. The user in the step above receives email about that failed job.

**Comment by freekmurze** [comment]
We cannot reproduce this. Please PR a failing test for us to fix.
