### ISSUE TITLE
Laravel 9.0.1 won't work because of composer setting

### ISSUE THREAD

**Issue by theupriser** [spatie/laravel-failed-job-monitor#69]
Hi!

I'm trying to install this on laravel 9.0.1 but that won't work because of this:

`
"require" : {
        "php" : "^8.0",
        "laravel/framework" : "^7.0|^8.0|9.0",
        "spatie/laravel-package-tools": "^1.6"
    },
`

laravel framework should use ^9.0 right?

Thanks!

**Comment by freekmurze** [comment]
Thanks for reporting, this has been fixed in the latest release.

**Comment by theupriser** [comment]
thanks!
