### ISSUE TITLE
Slack channel not supported?

### ISSUE THREAD

**Issue by ulfie22** [spatie/laravel-failed-job-monitor#72]
I installed per documentation - email notification works fine. I added a Slack webhook, but when I intentionally failed a job, I got `Driver [slack] not supported`. Here is a link (from Ray) to the Flare error: 

https://flareapp.io/share/w5Bzlpz5#F51

Thanks for your help!

**Comment by freekmurze** [comment]
You probably didn't install the Slack driver as mentioned in the Laravel docs: https://laravel.com/docs/master/notifications#slack-notifications
