### ISSUE TITLE
**[QUESTION]** 1 report for multiple failures

### ISSUE THREAD

**Issue by loekiedepo** [spatie/laravel-failed-job-monitor#8]
Is there a way to use this package in such a way that it bundles multiple failed jobs together in 1 report? My app has around 100 queued jobs at any given time (up to 5000) and I'd hate to spam the future admin with tens of emails per day when a single report per day would be sufficient.

If this isn't possible with this package, I'll find some other solution, but your package looks really promising and easy to implement.

**Comment by freekmurze** [comment]
If the code to create such a digest is not too complex, I'd consider accepting a PR that adds this to the package.

**Comment by loekiedepo** [comment]
I found it easier to just use Laravel's built in Task Scheduler. I retrieve the failed jobs from the `failed_table` at noon and midnight every day, drop those failed jobs into an email and then send that email.

Since this is actually really easy to implement without a package, I say this issue can be closed.
